Repository newrelic/newrelic-cli, pull requests merged in 2020-04, with the labels that each got.

#174 fix(profile): Fix case sensitivity of region
  go.mod
  go.sum
  internal/client/client.go
  internal/credentials/command.go
  internal/credentials/credentials.go
  internal/credentials/profiles.go
  internal/credentials/profiles_integration_test.go
  internal/credentials/profiles_test.go
Labels: bug, priority:blocker

#179 chore(client): Sanitize Region override
  internal/client/client.go
  internal/client/client_integration_test.go
Labels: bug

#181 Region fix (again)
  go.mod
  internal/credentials/profiles.go
  internal/credentials/profiles_integration_test.go
Labels: bug

#187 Custom release note generation
  .chglog/CHANGELOG.tpl.md
  build/document.mk
  build/release.mk
Labels: documentation

#183 chore(newrelic): Disable date printing on generated documentation
  cmd/newrelic/command.go
Labels: documentation

#188 Output refactor + formatting options
  cmd/newrelic/command.go
  go.mod
  internal/apm/command_application.go
  internal/apm/command_deployment.go
  internal/entities/command_search.go
  internal/entities/command_tags.go
  internal/nerdgraph/command_query.go
  internal/nerdstorage/command_collection.go
  internal/nerdstorage/command_document.go
  internal/output/config.go
  internal/output/json.go
  internal/output/output.go
  internal/output/print.go
  internal/output/yaml.go
  internal/workload/command_workload.go
Labels: enhancement, refactor, size:M

#197 Fix: Goreleaser Release Notes
  .goreleaser.yml
Labels: bug

#198 Fix: increase coverage of make snapshot
  build/release.mk
Labels: enhancement

#220 Move from ID to GUID for Workload get, per API change
  go.mod
  go.sum
  internal/workload/command_workload.go
Labels: breaking-change, priority:high, refactor, size:S

#221 chore(build): Remove README references and CircleCI config
  .circleci/config.yml
  README.md
Labels: documentation, refactor, size:S

#222 Release/v0.8.0
  CHANGELOG.md
  docs/cli/newrelic_workload_get.md
Labels: enhancement, size:S

#223 fix(build): Ignore scoop commit messages
  build/lint.mk
Labels: priority:blocker, size:S

#224 fix(release): fix relative path in WiX project
  build/package/msi/NewRelicCLIInstaller/Product.wxs
Labels: bug, size:S

#226 chore(build): Add stale bot config
  .github/stale.yml
Labels: enhancement, priority:low, size:S

#236 chore(deps): dep updates
  go.mod
  go.sum
Labels: dependencies

#241 Fix linting in Github actions
  .github/workflows/compile.yml
  .github/workflows/test.yml
Labels: bug, size:S

#240 Update mapstructure and tools
  go.mod
  go.sum
Labels: dependencies, size:S
