Repository newrelic/newrelic-cli, pull requests merged in 2021-07, with the labels that each got.

#989 refactor(install): eliminate dependency on open-install-library
  .gitignore
  Makefile
  README.md
  build/recipes.mk
  build/release.mk
  build/test.mk
  internal/install/recipe_installer.go
  internal/install/recipes/embedded_recipe_fetcher.go
  internal/install/recipes/embedded_recipe_fetcher_integration_test.go
  internal/install/recipes/files/.keep
  internal/install/recipes/service_recipe_fetcher.go
  internal/install/recipes/service_recipe_fetcher_test.go
Labels: refactor

#1006 fix(install-events-service): emit canceled recipe statuses correctly
  internal/install/execution/installevents_reporter.go
  internal/install/execution/installevents_reporter_unit_test.go
Labels: bug

#1012 chore(tutone): update generated code
  internal/install/types/types.go
Labels: enhancement

#1014 fix: failure events
  internal/install/execution/installevents_reporter.go
  internal/install/execution/installevents_reporter_unit_test.go
Labels: bug
